library(reshape2)
library(ggplot2)
library(lubridate)
library(dplyr)
library(readr)

setwd("C:/Users/adars/OneDrive/Escritorio/ProjecteLolShiny/Data")
data_lec <- read_csv("PlayerStats.csv")
data_lec$KP <- as.numeric(gsub("%", "", data_lec$KP))
data_lec$`DTH%` <- as.numeric(gsub("%", "", data_lec$`DTH%`))
ggplot(data_lec, aes(x = KP, y = `DTH%`)) + geom_point(color = "blue", size = 3)
